version: 0.2

phases:
  install:
    runtime-versions:
      - nodejs:latest
    commands:
      - npm i
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - npm run build

artifacts:
  exclude-paths:
    - ./build
    - ./node_modules